# Generated by Django 3.0 on 2020-04-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='task_amount',
            field=models.IntegerField(null=True),
        ),
    ]
