# Generated by Django 3.0 on 2020-04-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_amount',
            field=models.IntegerField(null=True),
        ),
    ]
