# Generated by Django 3.0 on 2020-03-01 18:43

from django.db import migrations
import my_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0002_auto_20200301_1842'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', my_auth.models.MyUserManager()),
            ],
        ),
    ]
